/*
* generated by Xtext
*/
package org.becausecucumber.eclipse.plugin.ui.outline;

import org.becausecucumber.eclipse.plugin.cucumber.Step;
import org.becausecucumber.eclipse.plugin.cucumber.Table;

/**
 * Customization of the default outline structure.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
public class CucumberOutlineTreeProvider extends org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider {

	protected boolean _isLeaf(Table modelElement) {
		// do not allow expansion of table nodes
		return true;
	}

	protected boolean _isLeaf(Step modelElement) {
		// only allow expansion of step nodes with tables
		return modelElement.getTables().isEmpty() && modelElement.getCode() == null;
	}
}
