/*
* generated by Xtext
*/
package org.becausecucumber.eclipse.plugin;

import org.becausecucumber.eclipse.plugin.CucumberStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CucumberStandaloneSetup extends CucumberStandaloneSetupGenerated{

	public static void doSetup() {
		new CucumberStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

