/*
 * generated by Xtext
 */
package org.becausecucumber.eclipse.plugin;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CucumberRuntimeModule extends org.becausecucumber.eclipse.plugin.AbstractCucumberRuntimeModule {

	
	// contributed by org.eclipse.xtext.generator.validation.JavaValidatorFragment
		@org.eclipse.xtext.service.SingletonBinding(eager=true)	public Class<? extends org.becausecucumber.eclipse.plugin.validation.CucumberJavaValidator> bindCucumberJavaValidator() {
			return org.becausecucumber.eclipse.plugin.validation.CucumberJavaValidator.class;
		}
		
		

}
