/*
 * generated by Xtext
 */
package org.becausecucumber.eclipse.plugin.formatting;

import com.google.inject.Inject;
import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.becausecucumber.eclipse.plugin.services.CucumberGrammarAccess;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class CucumberFormatter extends AbstractDeclarativeFormatter {
	
	@Inject
	private CucumberGrammarAccess grammarAccess; 
	
	@Override
	protected void configureFormatting(FormattingConfig c) {
// It's usually a good idea to activate the following three statements.
// They will add and preserve newlines around comments
//		c.setLinewrap(0, 1, 2).before(grammarAccess.getSL_COMMENTRule());
//		c.setLinewrap(0, 1, 2).before(grammarAccess.getML_COMMENTRule());
//		c.setLinewrap(0, 1, 1).after(grammarAccess.getML_COMMENTRule());
		
		c.setLinewrap(0, 1, 2).before(grammarAccess.getSL_COMMENTRule());
		//c.setLinewrap(0, 1, 2).before(grammarAccess.getML_COMMENTRule());
		//c.setLinewrap(0, 1, 1).after(grammarAccess.getML_COMMENTRule());
        c.setNoSpace().after(grammarAccess.getSTEP_KEYWORDRule());
		
		c.setIndentationIncrement().before(grammarAccess.getNarrativeRule());
		c.setIndentationDecrement().after(grammarAccess.getNarrativeRule());
		c.setIndentationIncrement().before(grammarAccess.getStepRule());
		c.setIndentationDecrement().after(grammarAccess.getStepRule());
		c.setIndentationIncrement().before(grammarAccess.getExamplesRule());
		c.setIndentationDecrement().after(grammarAccess.getExamplesRule());
		c.setIndentationIncrement().before(grammarAccess.getTableRule());
		c.setIndentationDecrement().after(grammarAccess.getTableRule());
		c.setIndentationIncrement().before(grammarAccess.getDocStringRule());
		c.setIndentationDecrement().after(grammarAccess.getDocStringRule());

		c.setNoLinewrap().around(grammarAccess.getStepDescriptionRule());
	}
}
