/*
 * generated by Xtext
 */
package org.becausecucumber.eclipse.plugin.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CucumberAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/becausecucumber/eclipse/plugin/parser/antlr/internal/InternalCucumber.tokens");
	}
}
